import { NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

export async function POST(req: Request) {
  try {
    const payload = await req.json();

    // Check if the payload is the end-of-call report from Vapi
    if (payload.message?.type === "end-of-call-report") {
      const { analysis, call } = payload.message;
      const summary = analysis?.summary;
      
      // Extract the custom variables we passed when starting the call
      // Vapi puts custom variables in call.assistantOverrides.variableValues or call.assistant.variableValues
      const variableValues = call?.assistantOverrides?.variableValues || call?.assistant?.variableValues || {};
      
      const { userId, companionId } = variableValues;

      if (!userId || !companionId) {
        return NextResponse.json(
          { error: "Missing userId or companionId in Vapi variables" },
          { status: 400 }
        );
      }

      // Connect to Supabase to save the memory
      const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
      const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;
      const supabase = createClient(supabaseUrl, supabaseAnonKey);

      // We insert a new record so getCompanionMemory can combine all previous summaries
      const { error } = await supabase.from("session_history").insert({
        companion_id: companionId,
        user_id: userId,
        summary: summary || "No summary was generated by Vapi.",
      });

      if (error) {
        console.error("Failed to save memory to Supabase:", error.message);
        return NextResponse.json({ error: error.message }, { status: 500 });
      }

      return NextResponse.json({ success: true, message: "Memory saved" });
    }

    // For any other Vapi webhook events, return a normal 200 OK
    return NextResponse.json({ success: true });
  } catch (error: any) {
    console.error("Vapi Webhook Processing Error:", error.message);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
